version: '3'
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/build:/frontend/build
  backend:
    build:
      context: ./backend
    volumes:
      - ../images:/images
    environment:
      - JASYPT_PASSWORD=ssapilogue104EShjDKkhHS
    ports:
      - "8080:8080"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/frontend/build
      - ../images:/images
    depends_on:
      - backend
      - frontend
