version: '3'
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/build:/frontend/build

  backend:
    ports:
      - "8080:8080"
  nginx:
    container_name: nginx
    image: "nginx:latest"
    ports:
      - "80:80"
    depends_on:
      - spring